language: python
services: memcached

matrix:
  include:
  - python: "3.6"
    env: TOX_ENV=py36-django22
  - python: "3.7"
    env: TOX_ENV=py37-django22
  - python: "3.7"
    env: TOX_ENV=py37-django30
  - python: "3.8"
    env: TOX_ENV=py38-django31
  - python: "3.9"
    env: TOX_ENV=py39-django31
  - python: "3.9"
    env: TOX_ENV=py39-django32

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
